version: '3.1'
services:
  mockly-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mockly-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  client:
    container_name: mockly-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
  api:
    container_name: mockly-api
    build:
      context: ./server/api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./server/api/src:/app/src
  feedback-service:
    container_name: mockly-feedback-service
    build:
      context: ./server/feedback-service
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
       - ./server/feedback-service/src:/app/src
  matching-service:
    container_name: mockly-matching-service
    build:
      context: ./server/matching-service
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    volumes:
      - ./server/matching-service/src:/app/src
  payment-service:
    container_name: mockly-payment-service
    build:
      context: ./server/payment-service
      dockerfile: Dockerfile
    ports:
      - 3004:3004
    volumes:
      - ./server/payment-service/src:/app/src
  profile-service:
    container_name: mockly-profile-service
    build:
      context: ./server/profile-service
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    volumes:
      - ./server/profile-service/src:/app/src